// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04EQK5JfX88tX1GBt3rw3bg7oXQmSuC0',
    appId: '1:620892733725:web:0ba7ddb631a6b392fd21f4',
    messagingSenderId: '620892733725',
    projectId: 'karaoke-list-project',
    authDomain: 'karaoke-list-project.firebaseapp.com',
    databaseURL: 'https://karaoke-list-project-default-rtdb.firebaseio.com',
    storageBucket: 'karaoke-list-project.appspot.com',
    measurementId: 'G-GS56EQRHJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVymnRV8Ll6s7DZWGx6GluzmCB7_P0IqY',
    appId: '1:620892733725:android:1546468c0bd8df8dfd21f4',
    messagingSenderId: '620892733725',
    projectId: 'karaoke-list-project',
    databaseURL: 'https://karaoke-list-project-default-rtdb.firebaseio.com',
    storageBucket: 'karaoke-list-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWm8vilXLkb3Fr8Hr3RTigdiv4scI6ZR4',
    appId: '1:620892733725:ios:b7ce1d7b3a6b51d7fd21f4',
    messagingSenderId: '620892733725',
    projectId: 'karaoke-list-project',
    databaseURL: 'https://karaoke-list-project-default-rtdb.firebaseio.com',
    storageBucket: 'karaoke-list-project.appspot.com',
    iosBundleId: 'com.kikuyukik.karalis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWm8vilXLkb3Fr8Hr3RTigdiv4scI6ZR4',
    appId: '1:620892733725:ios:318fbb5199b5ed0dfd21f4',
    messagingSenderId: '620892733725',
    projectId: 'karaoke-list-project',
    databaseURL: 'https://karaoke-list-project-default-rtdb.firebaseio.com',
    storageBucket: 'karaoke-list-project.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
